# Generated by Django 4.2.4 on 2023-08-27 04:53

import MindED.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MindED', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='edad',
            field=models.IntegerField(),
        ),
    ]
