# Generated by Django 4.2.4 on 2023-08-27 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MindED', '0002_paciente_edad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='fecha_nacimiento',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='edad',
            field=models.IntegerField(max_length=2),
        ),
        
    ]
