# Generated by Django 4.2.5 on 2023-09-08 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MindED', '0003_remove_paciente_fecha_nacimiento_alter_paciente_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='edad',
            field=models.IntegerField(),
        )
    ]
